apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${traefik_namespace:=forgetToConfigure}
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: regcred
    files:
      - .dockerconfigjson=./.dockerconfigjson
    type: kubernetes.io/dockerconfigjson
