apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-install
  namespace: ${traefik_namespace:=forgetToConfigure}
spec:
  patches:
    - patch: |
        - op: replace
          path: /spec/chart/spec/version
          value: ${traefik_version:=forgetToConfigure}
      target:
          kind: HelmRelease
