apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-customize
  namespace: ${traefik_namespace:=forgetToConfigure}
spec:
  dependsOn:
    - name: traefik-install
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./fluxcd/infrastructure/base/traefik/custom
  targetNamespace: ${traefik_namespace:=forgetToConfigure}
  timeout: 2m
  prune: true
