apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-install
  namespace: ${traefik_namespace:=forgetToConfigure}
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./fluxcd/infrastructure/base/traefik/install
  targetNamespace: ${traefik_namespace:=forgetToConfigure}
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: ${traefik_namespace:=forgetToConfigure}
  timeout: 2m
  prune: true
