apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${traefik_namespace:=forgetToConfigure}
resources:
- traefik-tls-store.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: traefik-tls-certificate
    files:
      - tls.key=./cert/gitops.jwausle.de.key
      - tls.crt=./cert/gitops.jwausle.de.pem
