apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/infrastructure/localhost
  prune: true
  validation: client
  postBuild:
    substitute:
      traefik_namespace: "traefik"
      traefik_version: "10.9.1"
      weave_namespace: "weave"
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik
  timeout: 2m
