apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: services
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./fluxcd/services/localhost
  prune: true
  validation: client
  postBuild:
    substitute:
      app_namespace: "example"
      app_branch: "master"
