apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-customize
  namespace: ${weave_namespace:=forgetToConfigure}
spec:
  dependsOn:
    - name: weave-install
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./fluxcd/infrastructure/base/weave/custom
  targetNamespace: ${weave_namespace:=forgetToConfigure}
  timeout: 2m
  prune: true
