apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: whoami-helmrelease-indirect-2
  namespace: ${app_namespace:=forgetToConfigure}
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: whoami-helmrelease-indirect-2
  path: ./helmcharts/helmreleases/indirect-2
  targetNamespace: ${app_namespace:=forgetToConfigure}
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: whoami-helmrelease-indirect-2
      namespace: ${app_namespace:=forgetToConfigure}
  timeout: 1m
  prune: true
