apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: whoami-helmrelease-indirect-2
spec:
  gitImplementation: go-git
  interval: 1m
  url: https://github.com/jwausle/gitops.fluxcd.git
  ref:
    branch: ${app_branch:=forgetToConfigure}
  timeout: 20s
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/helmcharts
