apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: weave-tls
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: weave-weave-gitops
          port: http
  tls: {}
