apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami-helmrelease-indirect-2
spec:
  chart:
    spec:
      chart: helmcharts/whoami
      sourceRef:
        kind: GitRepository
        name: whoami-helmrelease-indirect-2
  interval: 1m0s
  values:
    app:
      path: "whoami-helm4"
