apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami-helmchart
spec:
  chart:
    spec:
      chart: helmcharts/whoami
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1m0s
  values:
    app:
      path: "whoami-helm2"
